- name: Deployment for Opal (native debian package deployment)
  hosts: opal
  vars:
    opal:
      version: 2.16.0
      administrator:
        username: administrator
        password: xxxxx
    rserver:
      version: 1.4.0
    ci: false
    apache2:
      ssl: 
        default:
          enabled: false
        letsencrypt:
          enabled: true
    firewall:
      enabled: true
      ranges: 
        # university range
        - x.x.x.x/x
        # cental analysis server - please ask molgenis-operations@umcg.nl for details
        - x.x.x.x/32
    mysql:
      root_db_password: "xxxxx" 
      user:
        name: opal
        password: "xxxxx"
  roles:
   - ubuntu_init
   - ubuntu_mongodb
   - ubuntu_opal
   - apache2
   - apache2_ssl
   - apache2_ssl_letsencrypt
   - firewall