---
- name: create certificate-directories for SSL
  file:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}/
    state: directory
  when: apache2.ssl.default.enabled

- name: install SSL certs
  copy:
    content: "{{ item }}"  
    dest: "/etc/pki/tls/certs/{{ inventory_hostname }}/{{ item }}"
  with_items:
    - certificate.crt
    - private.key
    - serverchain.crt
  when: apache2.ssl.default.enabled

- name: copy SSL config file
  template: 
    src: options-ssl-httpd.j2 
    dest: /etc/httpd/conf.d/options-ssl-httpd.conf
  when: apache2.ssl.default.enabled

- name: install Apache2 virtualhost configuration
  template: 
    src: opal_ssl.j2
    dest: /etc/Apache2/conf.d/{{ inventory_hostname }}.conf
  when: apache2.ssl.default.enabled
  notify: restart apache2