- name: Install Oracle Java JDK 8
  apt:
    state: latest
    pkg: 
    - openjdk-8-jdk 
    - openjdk-8-jre
  become: true

- name: Add Opal key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80' 
    id: 379CE192D401AB61
  become: true

- name: Add Opal repository
  apt_repository: 
    repo: 'deb https://dl.bintray.com/obiba/deb all main'
    state: present
  become: true

- name: Install Opal and dependencies
  apt:
    pkg: 
      - opal={{ opal.version }}
      - opal-rserver={{ rserver.version }}
      - opal-python-client
    state: present
  become: true

- name: hash Opal administrator password
  shell: echo -n {{ opal.administrator.password }} | xargs java -jar /usr/share/opal/tools/lib/obiba-password-hasher-*-cli.jar 2>&1 | tail -n 1 
  register: hashed_opal_admin_password

- name: set the Opal administrator password
  shell: cat /etc/opal/shiro.ini | sed -e 's,^administrator\s*=.*\,,administrator=\"{{ hashed_opal_admin_password.stdout }}\"\,,' > /tmp/shiro.ini && mv /tmp/shiro.ini /etc/opal/shiro.ini

- name: overwrite default values for opal initscript to increase java heap
  template:
    src: opal
    dest: /etc/default/opal

- name: start and enable Opal (at boottime)
  systemd:
    name: opal
    state: started
  notify: start and enable opal

- name: Start and enable Opal RServe
  systemd:
    name: rserver
    state: started
  notify: start and enable rserver

- name: create database configuration directory
  file: 
    path: /etc/opal/config
    state: directory

- name: generate Opal ID's database configuration
  template:
    src: mysql_ids.json.j2
    dest: /etc/opal/config/mysqldb-ids.json
  
- name: generate Opal data database configuration
  template: 
    src: mysql_data.json.j2
    dest: /etc/opal/config/mysqldb-data.json

- name: configure Opal ID's database
  shell: cat /etc/opal/config/mysqldb-ids.json | opal rest -o http://localhost:8080 -u {{ opal.administrator.username }} -p "{{ opal.administrator.password }}" -m POST /system/databases --content-type "application/json"
  ignore_errors: true

- name: configure Opal data database
  shell: cat /etc/opal/config/mysqldb-data.json | opal rest -o http://localhost:8080 -u {{ opal.administrator.username }} -p "{{ opal.administrator.password }}" -m POST /system/databases --content-type "application/json"
  ignore_errors: true

- name: configure DataSHIELD
  shell: opal rest -o http://localhost:8080 -u {{ opal.administrator.username }} -p "{{ opal.administrator.password }}" -m POST /datashield/packages?name=datashield
  ignore_errors: true