---
- name: install Apache2
  apt: 
    name: 
      - apache2 
      - mod_ssl
    state: installed
  become: true

- name: delete default files in Apache2 conf.d directory
  file:
    state: absent
    path: /etc/apache2/conf.d/{{ item }}
  with_items:
    - autoindex.conf
    - README
    - userdir.conf
    - welcome.conf
    - ssl.conf

- name: install Apache2 virtualhost configuration
  template: 
    src: opal.j2
    dest: /etc/apache2/conf.d/{{ inventory_hostname }}.conf
  notify: restart apache2